### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by csocrate** [csocrate/sports-analytics-dashboard#17]
**Description**
- Clean code files like components, assets and update features for good practices.

**Tasks**
- [x] Add width and height props to LineChart and RadialBarChart components
- [x] Improve api service file
- [x] Update style
- [x] Add comments, update variable names...
- [x] Update README file
