### ISSUE TITLE
Getting NaN errors on LineChart and RadarChart  + invalid prop value on RadialBarChart

### ISSUE THREAD

**Issue by csocrate** [csocrate/sports-analytics-dashboard#18]
**Description**
- Getting `NaN` error on LineChart component : <g> attribute transform: Expected number, "translate(NaN,0)".
-  Getting `NaN` error on RadarChart component : <polygon> attribute points: Expected number, "NaN,NaN,NaN,NaN,…".
- Getting failed prop type on  RadialBarChart component: Invalid prop `value` of type `string`.

**Tasks**
- [x] Fix `NaN` errors on LineChart 
- [x] Fix `NaN` errors on RadarChart 
- [x] Fix Invalid prop `value` RadialBarChart
